theme: jekyll-theme-cayman

title: "職務経歴書"
description: ""
logo: ""
show_downloads: false

baseurl: "/a-tashiro7127"
url: "https://a-tashiro7127.github.io"

github:
  is_project_page: false
  is_user_page: false
